version: '3.8'

services:
  # Serviço 1: PostgreSQL 
  postgres:
    image: postgres:latest
    container_name: dcs-postgres
    restart: always
    environment:
      # Variáveis
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: etl_fakedata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

  # Serviço 2: pgAdmin 4
  pgadmin:
    image: dpage/pgadmin4
    container_name: dcs-pgadmin
    restart: always
    environment:
      # Credenciais de acesso ao pgAdmin
      PGADMIN_DEFAULT_EMAIL: fake123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres123
    ports:
      - "5050:80" 
    volumes:
      # Volume para persistir as configurações do pgAdmin
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - postgres-network
    depends_on:
      - postgres 
  fastapi:
    build: . 
    container_name: dcs-fastapi
    restart: always
    ports:     
      - "8000:8000"
    networks:
      - postgres-network 

# Definição das Redes
networks:
  postgres-network:
    driver: bridge

# Definição dos Volumes Nomeados
volumes:
  postgres_data:
